/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: b47e87482ba1bf9951583107157c02fb)
interface __BaseEnv_Env {
	DB: D1Database;
	ASSETS: Fetcher;
	S2K_USERNAME: string;
	S2K_PASSWORD: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
