/** Qserve Egypt product/service knowledge base. Seeded from sales-and-accessories.md. sell = 2× buy for catalog only. */

function faq(rows) {
  return rows.map(([qAr, aAr, qEn, aEn]) => ({ qAr, aAr, qEn, aEn }));
}

const CATALOG_FAQ = (nameAr, nameEn, sell, unitAr, unitEn, moq) =>
  faq([
    [
      `ما هو ${nameAr}؟`,
      `${nameAr} من كتالوج كيوسيرف مصر. سعر البيع ضعف سعر التوريد.`,
      `What is ${nameEn}?`,
      `${nameEn} from the Qserve Egypt catalog. Sell price is 2× supply cost.`,
    ],
    [
      "كم السعر؟",
      `سعر البيع ${sell} دولار / ${unitAr}. الحد الأدنى للطلب ${moq}. لا يوجد دفع بالبطاقة على الموقع — السلة ثم واتساب.`,
      "How much?",
      `Sell ${sell} USD / ${unitEn}. MOQ ${moq}. No card checkout — cart then WhatsApp.`,
    ],
    [
      "هل أضيفه للسلة؟",
      "نعم. المستهلكات وقطع الغيار تُضاف للسلة بالكميات. الأنظمة الكاملة تبقى بند «طلب عرض سعر».",
      "Can I add it to the cart?",
      "Yes. Consumables and spares go in the cart with quantities. Full systems stay as a quote line.",
    ],
    [
      "متى يصل للقاهرة؟",
      "الورق الثقيل بحراً (أسابيع). الطابعات والأشرطة والشرائح جواً تقريباً 5–10 أيام بعد التأكيد.",
      "Lead time to Cairo?",
      "Heavy paper by sea (weeks). Printers, ribbons and cards by air ~5–10 days after confirmation.",
    ],
  ]);

export const PRODUCTS = [
  {
    sku: "SYS-QUEUE",
    category: "system",
    priceRule: "quote",
    nameAr: "نظام انتظار العملاء",
    nameEn: "Queue management system",
    descAr:
      "نظام متكامل للتذاكر والشاشات ووحدات الاستدعاء والكيوسك. يُباع بدراسة موقع ثم عرض سعر — ليس سعر كتالوج.",
    descEn: "Tickets, displays, agent pads and kiosks. Sold after a site survey — not a catalog price.",
    page: "/queuing-system",
    keywords: ["طابور", "انتظار", "تذاكر", "شباك", "بنك", "فرع", "queue", "qms", "ticket", "3 شبابيك"],
    faq: faq([
      ["هل له سعر ثابت؟", "لا. نعاين الفرع ثم نرسل عرض سعر. يمكن وضع النظام في السلة كبند «طلب عرض سعر».", "Fixed price?", "No. We survey the site, then quote. You can park it in the cart as a quote line."],
      ["فرع بنك بثلاثة شبابيك؟", "باقة شائعة: كيوسك أو موزّع + شاشة صالة + 3 شاشات شباك + 3 وحدات نداء + رول. نضيفها للعرض.", "3-window bank branch?", "Typical pack: kiosk or dispenser, lobby screen, 3 counter displays, 3 pads, starter rolls — then a quote."],
      ["هل التقارير مجانية؟", "التشغيل الأساسي معه. تحليل الربح وقاعدة عملاء الفرع هو إضافة «كيوسيرف بصيرة» الاختيارية.", "Are reports free?", "Basic ops reports ship with the system. Profit/customer DB is the optional كيوسيرف بصيرة add-on."],
      ["صيانة؟", "ضمان سنتين مع قطع محلية. عقد صيانة سنوي بند منفصل على نفس العرض.", "Maintenance?", "Two-year warranty and local spares. Annual AMC is a separate line on the same quote."],
    ]),
  },
  {
    sku: "SYS-PKG-3WIN",
    category: "system",
    priceRule: "quote",
    nameAr: "باقة فرع 3 شبابيك",
    nameEn: "3-window branch package",
    descAr: "كيوسك/موزّع + شاشات + نداء لثلاثة شبابيك. سعر الأجهزة أرضية فقط — التركيب والصوت العربي والصيانة في العرض.",
    descEn: "Kiosk/dispenser + displays + callers for 3 windows. Hardware floor only — install, Arabic voice and AMC on the quote.",
    page: "/queuing-system",
    keywords: ["3 شبابيك", "فرع", "بنك", "عيادة صغيرة", "package", "three window"],
    faq: faq([
      ["هل أشتريها من السلة؟", "تُضاف كبند عرض سعر. ليست كاشير إلكتروني.", "Buy from cart?", "Add as a quote line — not card checkout."],
      ["ماذا تشمل؟", "مسار تذاكر، شاشة انتظار، ثلاث شاشات شباك، ثلاث وحدات نداء، وبادئ رول.", "What's included?", "Ticket path, waiting screen, 3 counter displays, 3 pads, starter rolls."],
      ["بصيرة؟", "اختياري على نفس العرض: قالب بنك + تجهيز + شهري/فرع.", "Basira?", "Optional on the same quote: bank template + setup + monthly per branch."],
    ]),
  },
  {
    sku: "SYS-NURSE",
    category: "system",
    priceRule: "quote",
    nameAr: "نظام استدعاء الممرضات",
    nameEn: "Nurse-call system",
    descAr: "أزرار سرير، شدّاد حمّام، لمبات ممر، ومحطة تمريض. عرض سعر وتركيب في المستشفى.",
    descEn: "Bed buttons, bathroom pulls, corridor lamps and nurse station. Quoted and installed on site.",
    page: "/nurse-call-system",
    keywords: ["ممرضات", "سرير", "مستشفى", "عيادة", "nurse", "call", "ward"],
    faq: faq([
      ["كود بلو؟", "لا نعلنه إلا إذا كان الجهاز يدعمه فعلاً. نركّز على النداء العادي والعاجل.", "Code blue?", "We do not advertise it unless the installed hardware really does it."],
      ["قطع الغيار؟", "أسلاك 6.35مم وأزرار ولمبات في الكتالوج بسعر 2×. النظام الكامل عرض سعر.", "Spares?", "Cords, buttons and lamps are catalog 2×. The full system is a quote."],
      ["عطل في السلك؟", "صف العطل في الدردشة أو /repair. نضيف السلك للسلة ونرسل فني إن لزم.", "Cord failed?", "Describe it in chat or /repair. We add the cord to the cart and dispatch if needed."],
    ]),
  },
  {
    sku: "SYS-KIOSK",
    category: "system",
    priceRule: "quote",
    nameAr: "كيوسك خدمة ذاتية",
    nameEn: "Self-service kiosk",
    descAr: "كيوسك بنكي / طعام / حكومي من المصنع. الشاشة والطابعة والبرنامج بعد المعاينة.",
    descEn: "Bank, food or government kiosk from the factory. Screen, printer and software after survey.",
    page: "/self-service-kiosks",
    keywords: ["كيوسك", "kiosk", "خدمة ذاتية", "طعام", "دفع"],
    faq: faq([
      ["الطابعة وقفت؟", "غالباً الرول أو القاطع أو المزود. نبحث الكتالوج: KP-802، رأس 80مم، رول 80×80، مزود 24V.", "Printer stopped?", "Usually roll, cutter or PSU. Catalog: KP-802, 80mm mechanism, 80×80 roll, 24V PSU."],
      ["سعر الكيوسك؟", "عرض سعر حسب المقاس 17 / 21.5 / 24 بوصة والتطبيق.", "Kiosk price?", "Quote by size 17 / 21.5 / 24 inch and application."],
      ["تعرف على الوجه؟", "لا نقدّم تعرف الوجه. الكيوسك للتذاكر والدفع والاستعلام.", "Face recognition?", "We do not offer face recognition. Kiosks are for tickets, payments and inquiry."],
    ]),
  },
  {
    sku: "SYS-CLOCK",
    category: "system",
    priceRule: "quote",
    nameAr: "ساعات مركزية",
    nameEn: "Master clock system",
    descAr: "ساعة رئيسية + ساعات فرعية NTP/PoE. النظام عرض سعر. الساعة التابعة في الكتالوج.",
    descEn: "Master + NTP/PoE slaves. System is quoted. Slave clocks are catalog.",
    page: "/central-clocks",
    keywords: ["ساعة", "clock", "ntp", "poe"],
    faq: faq([
      ["ساعة واحدة للفرع؟", "يمكن طلب ساعة تابعة من الكتالوج. الشبكة الكاملة عرض سعر.", "One clock?", "A slave clock can go in the cart. A campus network is a quote."],
    ]),
  },
  {
    sku: "SYS-SIGN",
    category: "system",
    priceRule: "quote",
    nameAr: "لافتات رقمية",
    nameEn: "Digital signage",
    descAr: "شاشات معلومات وإعلانات تُدار مركزياً. عرض سعر.",
    descEn: "Managed information/advertising screens. Quote.",
    page: "/digital-signage",
    keywords: ["لافتات", "signage", "led"],
    faq: faq([["سلة؟", "تُضاف كبند عرض سعر.", "Cart?", "Add as a quote line."]]),
  },
  {
    sku: "SYS-CSAT",
    category: "system",
    priceRule: "quote",
    nameAr: "تقييم الخدمة",
    nameEn: "Service evaluation / CSAT",
    descAr: "أجهزة وجوه/سمايل بعد الشباك. الطرفيات في الكتالوج؛ الشبكة عرض سعر.",
    descEn: "Smile terminals after the counter. Devices in catalog; a scored network is a quote.",
    page: "/service-evaluation",
    keywords: ["تقييم", "رضا", "csat", "smiley"],
    faq: faq([["جهاز واحد؟", "طرفية 8 بوصة في الكتالوج بسعر 2×.", "One terminal?", "8-inch CSAT terminal is a 2× catalog SKU."]]),
  },
  {
    sku: "SYS-MAP",
    category: "system",
    priceRule: "quote",
    nameAr: "خرائط تفاعلية",
    nameEn: "Interactive wayfinding",
    descAr: "توتم إرشاد للمستشفيات والمباني. عرض سعر + محتوى الخريطة.",
    descEn: "Wayfinding totems for hospitals. Quote plus map content.",
    page: "/interactive-maps",
    keywords: ["خريطة", "wayfinding", "إرشاد"],
    faq: faq([["هل فيه تعرف وجه؟", "لا. الإرشاد بدون هوية.", "Face ID?", "No. Wayfinding is anonymous."]]),
  },
  {
    sku: "SYS-BOARD",
    category: "system",
    priceRule: "quote",
    nameAr: "شاشات تفاعلية ذكية",
    nameEn: "Smart interactive boards",
    descAr: "شاشات 4K للتعليم والاجتماعات. عرض سعر.",
    descEn: "4K boards for classrooms and meetings. Quote.",
    page: "/smart-boards",
    keywords: ["سبورة", "board", "4k"],
    faq: faq([["سعر؟", "حسب المقاس والتركيب — عرض سعر.", "Price?", "By size and install — quote."]]),
  },
  {
    sku: "ANL-SETUP",
    category: "software",
    priceRule: "quote",
    nameAr: "كيوسيرف بصيرة — تجهيز",
    nameEn: "Qserve Basira — setup",
    descAr:
      "إضافة برمجية مخصّصة لكل عميل: تبني قاعدة عملاء فرعه من أجهزة كيوسيرف وتظهر أين يضيع الربح. ليست برنامجاً جاهزاً للجميع.",
    descEn: "Per-client add-on: builds that client's branch customer DB from Qserve devices and shows where profit leaks. Not a generic SaaS.",
    page: "/insights",
    keywords: ["بصيرة", "basira", "برنامج", "ربح", "تحليل", "software", "insights"],
    faq: faq([
      ["هل تُشترى من السلة بسعر ثابت؟", "لا. تُضاف كبند عرض سعر: تجهيز مرة + شهري/فرع. تعمل فقط مع نظام كيوسيرف.", "Fixed cart price?", "No. Quote line: one-time setup + monthly per branch. Needs Qserve OS on site."],
      ["بنك مقابل مستشفى؟", "قوالب مختلفة ثم ورشة تخصيص لحقولكم.", "Bank vs hospital?", "Different templates, then a workshop for your fields."],
      ["بيانات الزوار؟", "افتراضياً تشغيل الطابور بدون الرقم القومي أو الوجه. العميل هو المتحكم في البيانات.", "Visitor data?", "Default is operations, not national ID or face. The client is the data controller."],
    ]),
  },
  {
    sku: "ANL-BR",
    category: "software",
    priceRule: "quote",
    nameAr: "كيوسيرف بصيرة — اشتراك فرع",
    nameEn: "Qserve Basira — branch subscription",
    descAr: "شهري لكل فرع يعمل فيه النظام: لوحة عربية وملخص واتساب.",
    descEn: "Monthly per live branch: Arabic dashboard and WhatsApp digest.",
    page: "/insights",
    keywords: ["شهري", "فرع", "اشتراك", "monthly"],
    faq: faq([["بدون تجهيز؟", "الاشتراك يحتاج ANL-SETUP مرة لكل عميل.", "Without setup?", "Subscription needs a one-time ANL-SETUP per client."]]),
  },
  {
    sku: "ANL-TPL-BANK",
    category: "software",
    priceRule: "quote",
    nameAr: "قالب بصيرة للبنك",
    nameEn: "Basira bank template",
    descAr: "خدمات، شبابيك، انتظار، تحويل للكيوسك.",
    descEn: "Services, windows, wait SLA, kiosk deflection.",
    page: "/insights",
    keywords: ["بنك", "bank", "شباك"],
    faq: faq([["هل يكفي القالب؟", "بداية نعم، ثم نسمّي خدماتكم في الورشة.", "Is the template enough?", "It is the start; we rename your services in the workshop."]]),
  },
  {
    sku: "ANL-TPL-HOSP",
    category: "software",
    priceRule: "quote",
    nameAr: "قالب بصيرة للمستشفى",
    nameEn: "Basira hospital template",
    descAr: "عيادات، عدم حضور، زمن نداء إن وُجد. ليست تشخيصات.",
    descEn: "Clinics, no-shows, nurse-call time if installed. Not diagnoses.",
    page: "/insights",
    keywords: ["مستشفى", "عيادة", "hospital"],
    faq: faq([["بيانات صحية؟", "حساسة قانوناً. القالب الافتراضي زيارات وعيادات فقط.", "Health data?", "Sensitive under PDPL. Default template is visits/clinics only."]]),
  },
  {
    sku: "ANL-TPL-GOV",
    category: "software",
    priceRule: "quote",
    nameAr: "قالب بصيرة لجهة حكومية",
    nameEn: "Basira government template",
    descAr: "نوافذ ومعاملات وSLA — بدون الرقم القومي افتراضياً.",
    descEn: "Windows, transactions, published SLA — no national ID by default.",
    page: "/insights",
    keywords: ["حكومة", "government", "نافذة"],
    faq: faq([["الرقم القومي؟", "ليس حقلاً افتراضياً. يُسعَّر تخصيصاً إن طلبه المناقصة.", "National ID?", "Not a default field. Priced customization if a tender demands it."]]),
  },
  {
    sku: "SVC-EMERG",
    category: "repair",
    priceRule: "quote",
    nameAr: "نداء طوارئ / خروج فني",
    nameEn: "Emergency technician callout",
    descAr: "خروج فني للقاهرة الكبرى عند توقف الجهاز، بدون عقد. أجرة الزيارة + الساعة + القطع بسعر بيع الكتالوج. بعد الدوام مدفوع — لسنا 24/7.",
    descEn: "Greater Cairo callout when a device is down and there is no contract. Visit fee + hourly + parts at catalog sell. After-hours is paid — we are not 24/7.",
    page: "/maintenance",
    keywords: ["عطل", "وقفت", "تصليح", "صيانة", "فني", "طوارئ", "repair", "down", "jam", "emergency", "callout"],
    faq: faq([
      ["ماذا يشمل؟", "زيارة موقع في ساعات العمل، تشخيص، واستبدال قطعة من مخزون القاهرة إن وُجدت. القطع تُفوتر بسعر الكتالوج (2× التوريد).", "What's covered?", "On-site visit in business hours, diagnosis, and a Cairo-stock spare if we have it. Parts bill at catalog sell (2× supply)."],
      ["زمن الاستجابة؟", "القاهرة الكبرى: نفس اليوم إن وصل الطلب قبل 14:00، وإلا صباح العمل التالي. الإسكندرية والدلتا: يوم العمل التالي. الصعيد: حتى 48 ساعة.", "Response time?", "Greater Cairo: same day if logged before 14:00, else next business morning. Alex & Delta: next business day. Upper Egypt: up to 48 hours."],
      ["هل أنتم 24/7؟", "لا. السبت–الخميس 9:00–18:00. الجمعة عطلة. بعد الدوام = هذا البند بسعر أعلى، وليس شعاراً مجانياً.", "24/7?", "No. Sat–Thu 09:00–18:00. Friday closed. After hours is this SKU at a higher rate — not a free slogan."],
      ["عندي عقد صيانة؟", "إن وُجد AMC-STD أو AMC-PLUS فالزيارة ضمن التذاكر المتعاقد عليها (أيام العمل). بدون عقد هذا البند أغلى — نضيف العقد للسلة كعرض سعر.", "I already have AMC?", "With AMC-STD/PLUS the visit is a contract ticket in business hours. Without a contract this line costs more — we add the annual contract to the cart as a quote."],
      ["طابعة الكيوسك وقفت؟", "نبحث الكتالوج: رول، قاطع، رأس 80مم، مزود 24V، KP-802. نضيف القطع للسلة + بند الفني أو العقد.", "Kiosk printer stopped?", "We search the KB: roll, cutter, 80mm mechanism, 24V PSU, KP-802. Parts go in the cart plus a technician or AMC line."],
    ]),
  },
  {
    sku: "SVC-REMOTE",
    category: "repair",
    priceRule: "quote",
    nameAr: "تشخيص عن بُعد ثم زيارة",
    nameEn: "Remote diagnosis then visit",
    descAr: "واتساب أو سطح مكتب أولاً. السيارة تُرسل فقط إذا لزم. أجرة التشخيص تُحتسب حتى لو لم نخرج.",
    descEn: "WhatsApp or remote desktop first. A van only if needed. The remote fee is kept even if we do not dispatch.",
    page: "/maintenance",
    keywords: ["عن بعد", "remote", "teamviewer", "واتساب فني"],
    faq: faq([
      ["ماذا يشمل؟", "جلسة تشخيص (واتساب فيديو / أي ديسك) وإرشاد المشغّل. إن لم يُحل العطل نحدد زيارة.", "What's covered?", "A WhatsApp/AnyDesk session and operator guidance. If it stays down we book a visit."],
      ["زمن الرد؟", "خلال ساعات العمل السبت–الخميس 9–6. ليس 24/7.", "Response?", "During Sat–Thu 09:00–18:00. Not 24/7."],
      ["قطع الغيار؟", "إن ظهرت حاجة لرول أو قاطع نضيفها للسلة فوراً.", "Spares?", "If a roll or cutter is needed we add it to the cart immediately."],
    ]),
  },
  {
    sku: "AMC-STD",
    category: "repair",
    priceRule: "quote",
    nameAr: "عقد صيانة سنوي",
    nameEn: "Annual maintenance contract",
    descAr: "عقد رعاية للنظام المركّب: زيارتان وقائيتان، تذاكر في ساعات العمل، قطع بسعر القائمة ناقص 10٪، يوم العمل التالي في القاهرة. ليس 2× علي بابا وليس 24/7.",
    descEn: "Care contract for an installed system: two preventive visits, business-hours tickets, parts at list minus 10%, next business day in Cairo. Not 2× Alibaba and not 24/7.",
    page: "/maintenance",
    keywords: ["عقد", "صيانة سنوية", "amc", "warranty", "after sale", "بعد البيع", "عندنا نظام", "مركب"],
    faq: faq([
      ["ماذا يغطي العقد؟", "زيارتان وقائيتان في السنة، تذاكر أعطال في ساعات العمل، خصم 10٪ على قطع الكتالوج، وأولوية على الزائر بدون عقد. العمالة أثناء الضمان مشمولة إذا استخدمتم ورق/قطع كيوسيرف.", "What's covered?", "Two preventive visits a year, business-hours fault tickets, 10% off catalog parts, priority over non-contract callouts. Warranty labour applies if you use Qserve paper/parts."],
      ["زمن الاستجابة؟", "القاهرة الكبرى: 4 ساعات هدف أو يوم العمل التالي. الإسكندرية والدلتا: يوم العمل التالي. الصعيد: 48 ساعة. لا نعد بزمن خارج ساعات العمل إلا ببند الطوارئ.", "Response time?", "Greater Cairo: 4-hour target or next business day. Alex & Delta: next business day. Upper Egypt: 48 hours. No after-hours SLA unless you buy emergency callout."],
      ["قطع الغيار؟", "من مخزون القاهرة الجديدة بسعر بيع الكتالوج ناقص 10٪ للتعاقدين. الرول والأحبار والأسلاك تُطلب من السلة.", "Spare parts?", "New Cairo stock at catalog sell minus 10% for contract holders. Rolls, ribbons and cords are ordered from the cart."],
      ["هل يشمل 24/7؟", "لا. السبت–الخميس 9:00–18:00، الجمعة عطلة. الطوارئ الليلية/الجمعة = SVC-EMERG مدفوع فوق العقد.", "Is it 24/7?", "No. Sat–Thu 09:00–18:00, Friday off. Nights/Friday = paid SVC-EMERG on top of the contract."],
      ["كيف يُسعَّر؟", "عادة 8–15٪ من قيمة النظام / سنة بعد حساب التكلفة. يظهر في السلة كبند «طلب عرض سعر» وليس رقماً وهمياً.", "How is it priced?", "Typically 8–15% of system value per year after cost. It sits in the cart as a quote line — no fake number."],
      ["عندي نظام كيوسيرف ويعطل؟", "نعم هذا المنتج. نضيف AMC-STD للسلة ونفتح صفحة الصيانة. إن أردتم بصيرة مع العقد نضع AMC-INS.", "We already have a Qserve system and it fails?", "This is the SKU. We add AMC-STD to the cart and open /maintenance. For Basira bundled, we add AMC-INS."],
    ]),
  },
  {
    sku: "AMC-PLUS",
    category: "repair",
    priceRule: "quote",
    nameAr: "عقد صيانة + احتياطي قطع",
    nameEn: "AMC plus on-site spare kit",
    descAr: "كل تغطية AMC-STD بالإضافة إلى صندوق قطع مقفل في موقعكم: طابعة بديلة + مزود + 20 رول + 5 أسلاك نداء حسب النظام.",
    descEn: "All AMC-STD cover plus a locked spare kit on your site: spare printer, PSU, 20 rolls and 5 nurse cords as applicable.",
    page: "/maintenance",
    keywords: ["احتياطي", "kit", "plus", "صندوق قطع", "amc plus"],
    faq: faq([
      ["ماذا يزيد عن العقد العادي؟", "طقم قطع في الفرع حتى لا ينتظر الشباك الرول أو الطابعة. الطقم بسعر الكتالوج (2×) داخل عرض العقد.", "What's extra vs STD?", "A site kit so the window does not wait for a roll or printer. The kit is catalog 2× inside the contract quote."],
      ["الاستجابة؟", "نفس أيام العمل. الهدف أن العطل الشائع يُحل من الصندوق قبل وصول الفني.", "Response?", "Same business hours. Common faults clear from the kit before a technician arrives."],
      ["24/7؟", "لا. نفس ساعات المصنع. الطوارئ بند منفصل.", "24/7?", "No. Same factory hours. Emergency is a separate SKU."],
    ]),
  },
  {
    sku: "AMC-INS",
    category: "repair",
    priceRule: "quote",
    nameAr: "عقد صيانة + كيوسيرف بصيرة",
    nameEn: "AMC plus Qserve Basira",
    descAr: "AMC-PLUS مع إضافة بصيرة: تجهيز مخفّض أو مُعفى السنة الأولى، والاشتراك الشهري على نفس فاتورة الصيانة. عطل الكيوسك وعطل اللوحة عند بائع واحد.",
    descEn: "AMC-PLUS plus Basira: setup discounted or waived in year one, monthly on the same maintenance invoice. Kiosk down and dashboard down with one vendor.",
    page: "/maintenance",
    keywords: ["بصيرة", "amc-ins", "صيانة وتحليل", "basira bundle"],
    faq: faq([
      ["ماذا يشمل؟", "وقائي + احتياطي قطع + لوحة بصيرة لفرعكم (قالب ثم تخصيص). ليس برنامجاً عاماً.", "What's covered?", "Preventive + spare kit + your branch Basira board (template then customize). Not a generic app."],
      ["إن تعطّل الجهاز؟", "تذكرة صيانة في ساعات العمل، واللوحة تراقب فراغ الرول لتعيد الطلب قبل العطل.", "If hardware fails?", "A business-hours ticket, and the board watches empty-roll so you reorder before downtime."],
      ["24/7؟", "لا للأجهزة. اللوحة مستضافة؛ عطل الاستضافة يُعالج في ساعات العمل ما لم يُنص في المناقصة خلاف ذلك.", "24/7?", "Not for hardware. Hosting incidents are business hours unless a tender states otherwise."],
    ]),
  },
  {
    sku: "WTY-EXT",
    category: "repair",
    priceRule: "quote",
    nameAr: "تمديد ضمان",
    nameEn: "Warranty extension",
    descAr: "سنة أجهزة ثالثة مع عمالة المصنع. يستثني سوء الاستخدام والماء وورق الطرف الثالث الذي يغبر القاطع.",
    descEn: "Hardware year 3 with factory labour. Excludes abuse, water, and third-party paper that dusts the cutter.",
    page: "/maintenance",
    keywords: ["ضمان", "تمديد", "warranty", "year 3"],
    faq: faq([
      ["ما المغطى؟", "عيوب التصنيع وعمالة المصنع في السنة الثالثة.", "Covered?", "Manufacturing defects and factory labour in year 3."],
      ["ما غير المغطى؟", "الإساءة، الماء، وانحشار الرول الرخيص. ننصح بعقد AMC-STD فوق التمديد.", "Not covered?", "Abuse, water, and cheap-roll jams. We recommend AMC-STD on top of the extension."],
    ]),
  },
  {
    sku: "TRN-DAY",
    category: "repair",
    priceRule: "quote",
    nameAr: "تدريب مشغّلين",
    nameEn: "Operator training day",
    descAr: "نصف يوم أو يوم في الموقع للمشغّلين. البنوك توقّعه كبند في العرض.",
    descEn: "Half or full day on site for operators. Banks will sign it as a quote line.",
    page: "/maintenance",
    keywords: ["تدريب", "training", "مشغلين"],
    faq: faq([["هل مجاني للأبد؟", "لا. يوم مدفوع. إعادة التدريب بعد تغيير الطاقم بند جديد.", "Free forever?", "No. A paid day. Retraining after staff change is a new line."]]),
  },
  {
    sku: "SLA-HOSP",
    category: "repair",
    priceRule: "quote",
    nameAr: "اتفاقية مستوى خدمة مستشفى",
    nameEn: "Hospital SLA",
    descAr: "أولوية نداء الممرضات، هدف 4 ساعات في القاهرة، ومحطة سرير بديلة إن توفرت. لا نعد بكود بلو ما لم يكن الجهاز كذلك.",
    descEn: "Nurse-call priority, 4-hour Cairo target, loaner bed station if available. No code-blue promise unless the hardware does it.",
    page: "/maintenance",
    keywords: ["مستشفى", "sla", "4 ساعات", "تمريض"],
    faq: faq([
      ["الاستجابة؟", "هدف 4 ساعات داخل القاهرة في ساعات العمل. ليس 24/7 إلا إذا نُص في المناقصة وسُعّر.", "Response?", "4-hour target in Cairo during business hours. Not 24/7 unless the tender prices it."],
      ["كود بلو؟", "لا نكتبه في الـ SLA إلا إذا كان الجهاز يدعمه فعلاً.", "Code blue?", "Not in the SLA unless the installed hardware actually supports it."],
    ]),
  },
];

const CATALOG_SEED = [
  {
    sku: "TH-80X80",
    category: "consumable",
    nameAr: "رول حراري POS 80×80",
    nameEn: "Thermal POS roll 80×80",
    descAr: "رول تذاكر/إيصال 80×80 مم لم dispensers والكيوسك. بيع = 2× التوريد.",
    descEn: "80×80 mm ticket/receipt roll for dispensers and kiosks. Sell = 2× supply.",
    page: "/products/TH-80X80",
    buyUsd: 0.21,
    moq: 1000,
    unitAr: "رول",
    unitEn: "roll",
    supplier: "Alibaba",
    url: "https://www.alibaba.com/product-detail/Wholesale-Price-60g-65g-70g-57_1600863398493.html",
    notesAr: "بحر إلى العين السخنة. 50/كرتونة. جموميا أغلى.",
    notesEn: "Sea to Ain Sokhna; 50/ctn. Jumia is the price ceiling.",
    keywords: ["رول", "ورق", "حراري", "80", "roll", "thermal", "paper", "ticket"],
  },
  {
    sku: "TH-80X70",
    category: "consumable",
    nameAr: "رول حراري كيوسك 80×70",
    nameEn: "Kiosk thermal roll 80×70",
    descAr: "قطر 70 مم للهوبر الضيق في كيوسك البنوك.",
    descEn: "70 mm OD for tight kiosk hoppers.",
    page: "/products/TH-80X70",
    buyUsd: 0.4,
    moq: 1000,
    unitAr: "رول",
    unitEn: "roll",
    supplier: "Alibaba",
    url: "https://www.alibaba.it/product-detail/Factory-Wholesale-Customizable-Size-Thermal-Paper_10000041100782.html",
    notesAr: "حدّد القطر 70 مم عند الطلب.",
    notesEn: "Specify 70mm OD on the PO.",
    keywords: ["كيوسك", "رول", "70", "kiosk", "roll"],
  },
  {
    sku: "TH-60X60",
    category: "consumable",
    nameAr: "رول تذاكر طابور 60×60",
    nameEn: "Queue ticket roll 60×60",
    descAr: "2000 تذكرة، قلب 25.4 مم، أسلوب Q-matic المتوافق.",
    descEn: "2,000 tickets, 25.4 mm core, Q-matic-compatible style.",
    page: "/products/TH-60X60",
    buyUsd: 2,
    moq: 1000,
    unitAr: "رول",
    unitEn: "roll",
    supplier: "Made-in-China",
    url: "https://www.madeinchina.com/mall/show-Queue-Ticket-60X60mm-2000-PCS-Per-Roll-Q-Matic-Thermal-Paper-Roll_165630.html",
    notesAr: "بحر. تأكد مقاس الورق في الفرع قبل أول طلب.",
    notesEn: "Sea. Confirm ticket size on site before first PO.",
    keywords: ["60", "qmatic", "تذاكر", "queue ticket"],
  },
  {
    sku: "TH-57X50",
    category: "consumable",
    nameAr: "رول حراري 57 مم",
    nameEn: "57mm thermal roll",
    descAr: "لطابعات الشباك الصغيرة وأجهزة التقييم.",
    descEn: "Compact 58 mm printers and CSAT pads.",
    page: "/products/TH-57X50",
    buyUsd: 0.28,
    moq: 1000,
    unitAr: "رول",
    unitEn: "roll",
    supplier: "Alibaba",
    url: "https://www.alibaba.co.uk/product-detail/thermal-paper-till-roll-80x80-thermal_12000002377402.html",
    notesAr: "ليس رول كيوسك 80 مم.",
    notesEn: "Not an 80 mm kiosk roll.",
    keywords: ["57", "58", "صغير"],
  },
  {
    sku: "RFID-M1K",
    category: "consumable",
    nameAr: "كارت Mifare Classic 1K",
    nameEn: "Mifare Classic 1K card",
    descAr: "13.56MHz، CR80، أبيض قابل للطباعة.",
    descEn: "13.56 MHz, CR80, printable white.",
    page: "/mifare-card",
    buyUsd: 0.15,
    moq: 100,
    unitAr: "كارت",
    unitEn: "card",
    supplier: "Alibaba",
    url: "https://www.alibaba.com/product-detail/7-Byte-UID-Passive-MF-1K_1600505072497.html",
    notesAr: "عبوة 100: شراء 15 / بيع 30.",
    notesEn: "Pack of 100: buy 15 / sell 30.",
    keywords: ["mifare", "رفيد", "nfc", "كارت"],
  },
  {
    sku: "EM-4100",
    category: "consumable",
    nameAr: "كارت بروكسيمتي EM4100",
    nameEn: "EM4100 proximity card",
    descAr: "125 كيلوهرتز للحضور والبوابات.",
    descEn: "125 kHz for attendance and doors.",
    page: "/proximity-card",
    buyUsd: 0.09,
    moq: 200,
    unitAr: "كارت",
    unitEn: "card",
    supplier: "Alibaba",
    url: "https://www.alibaba.com/product-detail/125Khz-Proximity-ID-Card-Chip-EM_1600115789802.html",
    notesAr: "ليس Mifare.",
    notesEn: "Not Mifare.",
    keywords: ["proximity", "بروكسيمتي", "125", "em4100"],
  },
  {
    sku: "PVC-CR80",
    category: "consumable",
    nameAr: "كارت PVC أبيض CR80",
    nameEn: "Blank CR80 PVC card",
    descAr: "بدون شريحة — للطباعة فقط.",
    descEn: "No chip — print only.",
    page: "/id-card-printing",
    buyUsd: 0.05,
    moq: 1000,
    unitAr: "كارت",
    unitEn: "card",
    supplier: "Alibaba",
    url: "https://www.alibaba.com/product-detail/Hot-Selling-Standard-CR80-0-76mm_1600344160994.html",
    notesAr: "مع شريحة استخدم RFID-M1K.",
    notesEn: "Use RFID-M1K when a chip is required.",
    keywords: ["pvc", "طباعة", "blank"],
  },
  {
    sku: "RIB-EV-R3011",
    category: "consumable",
    nameAr: "شريط Evolis YMCKO متوافق",
    nameEn: "Evolis-compatible YMCKO ribbon",
    descAr: "حوالي 300 طبعة. تأكد Primacy مقابل Primacy 2.",
    descEn: "About 300 prints. Confirm Primacy vs Primacy 2.",
    page: "/id-card-printers",
    buyUsd: 40,
    moq: 2,
    unitAr: "شريط",
    unitEn: "ribbon",
    supplier: "Alibaba",
    url: "https://www.alibaba.fr/product-detail/Factory-Price-R5F008S130-Full-Panel-YMCKO_1601628347491.html",
    notesAr: "متوافق وليس High Trust.",
    notesEn: "Compatible, not Evolis High Trust.",
    keywords: ["evolis", "ribbon", "شريط", "ymcko"],
  },
  {
    sku: "RIB-ZC-250",
    category: "consumable",
    nameAr: "شريط Zebra YMCKO",
    nameEn: "Zebra YMCKO ribbon",
    descAr: "لطابعات ZC100/ZC300. تأكد رقم القطعة.",
    descEn: "For ZC100/ZC300. Confirm part number.",
    page: "/id-card-printers",
    buyUsd: 45,
    moq: 1,
    unitAr: "شريط",
    unitEn: "ribbon",
    supplier: "ID Zone",
    url: "https://www.idzone.com/800033-340.html",
    notesAr: "ZC300 أرقام مختلفة عن ZXP3.",
    notesEn: "ZC300 parts differ from ZXP3.",
    keywords: ["zebra", "zc300", "شريط"],
  },
  {
    sku: "PRN-XP-T80Q",
    category: "spare",
    nameAr: "طابعة تذاكر مكتبية 80 مم",
    nameEn: "80mm desktop ticket printer",
    descAr: "USB وقاطع — شباك الخدمة.",
    descEn: "USB + cutter for the counter.",
    page: "/products/PRN-XP-T80Q",
    buyUsd: 37,
    moq: 2,
    unitAr: "قطعة",
    unitEn: "pc",
    supplier: "Alibaba",
    url: "https://www.alibaba.com/product-detail/OCPP-80S-OCOM-300mm-s-High_1601215227374.html",
    notesAr: "ليست طابعة كيوسك مدمجة.",
    notesEn: "Not the embedded kiosk printer.",
    keywords: ["طابعة", "printer", "شباك", "xprinter"],
  },
  {
    sku: "KSK-KP802",
    category: "spare",
    nameAr: "طابعة كيوسك مدمجة KP-802",
    nameEn: "Embedded kiosk printer KP-802",
    descAr: "80 مم، USB/RS232/LAN، قاطع. بديل صيانة كيوسك البنوك.",
    descEn: "80 mm, USB/RS232/LAN, cutter. Bank kiosk drop-in spare.",
    page: "/products/KSK-KP802",
    buyUsd: 120,
    moq: 1,
    unitAr: "قطعة",
    unitEn: "pc",
    supplier: "Alibaba",
    url: "https://www.alibaba.com/product-detail/KP-802-80mm-Kiosk-Thermal-Printer_1601651355774.html",
    notesAr: "مخزون السيارة. جوّاً.",
    notesEn: "Van stock. Air.",
    keywords: ["طابعة", "كيوسك", "وقفت", "kp-802", "printer", "kiosk", "cutter"],
  },
  {
    sku: "TPH-80",
    category: "spare",
    nameAr: "رأس/آلية طباعة 80 مم مع قاطع",
    nameEn: "80mm print mechanism with cutter",
    descAr: "عندما يبهت الطبع أو يعلق الكاتر.",
    descEn: "When print fades or the cutter jams.",
    page: "/products/TPH-80",
    buyUsd: 32,
    moq: 5,
    unitAr: "قطعة",
    unitEn: "pc",
    supplier: "Alibaba",
    url: "https://www.alibaba.com/product-detail/3-Inch-80mm-SNBC-Kiosk-Thermal_1600902956973.html",
    notesAr: "صيانة كيوسك.",
    notesEn: "Kiosk repair.",
    keywords: ["قاطع", "كاتر", "رأس", "mechanism", "cutter", "jam"],
  },
  {
    sku: "PSU-24V25",
    category: "spare",
    nameAr: "مزود 24V لطابعة/كيوسك",
    nameEn: "24V PSU for printer/kiosk",
    descAr: "كيوسك ميت غالباً المزود.",
    descEn: "A dead kiosk is often the PSU.",
    page: "/products/PSU-24V25",
    buyUsd: 4.5,
    moq: 10,
    unitAr: "قطعة",
    unitEn: "pc",
    supplier: "Alibaba",
    url: "https://www.alibaba.com/product-detail/24V-2-5A-60W-3-Pin_60837003776.html",
    notesAr: "اطلب فيشة مصر/EU.",
    notesEn: "Order EU/EG plug.",
    keywords: ["باور", "مزود", "power", "psu", "24v", "ميت"],
  },
  {
    sku: "PSU-MW-24",
    category: "spare",
    nameAr: "مزود Mean Well 24V 150W",
    nameEn: "Mean Well 24V 150W PSU",
    descAr: "أصلي — تجنب الكلونات الرخيصة.",
    descEn: "Genuine — avoid cheap clones.",
    page: "/products/PSU-MW-24",
    buyUsd: 9.34,
    moq: 1,
    unitAr: "قطعة",
    unitEn: "pc",
    supplier: "Alibaba",
    url: "https://www.alibaba.com/product-detail/MEAN-WELL-LRS-150-24-Compact_1601371542104.html",
    notesAr: "مخزون السيارة.",
    notesEn: "Van stock.",
    keywords: ["mean well", "lrs", "24v"],
  },
  {
    sku: "NC-CORD-635",
    category: "spare",
    nameAr: "سلك نداء ممرضات 6.35 مم",
    nameEn: "6.35mm nurse-call cord",
    descAr: "قطعة الاستهلاك الأولى في الأجنحة. تأكد الفيشة.",
    descEn: "Ward wear item #1. Confirm the jack.",
    page: "/products/NC-CORD-635",
    buyUsd: 4.8,
    moq: 100,
    unitAr: "قطعة",
    unitEn: "pc",
    supplier: "Alibaba",
    url: "https://www.alibaba.com/product-introduction/1-4-6-35mm-Plug-Nurse_1600966237763.html",
    notesAr: "6.35 مقابل RJ45 مقابل DIN حسب اللوحة.",
    notesEn: "6.35 vs RJ45 vs DIN depending on the bed plate.",
    keywords: ["سلك", "ممرضة", "cord", "6.35", "nurse"],
  },
  {
    sku: "NC-BTN-2K",
    category: "spare",
    nameAr: "زر استدعاء ممرضات",
    nameEn: "Nurse-call button",
    descAr: "نداء + إلغاء، لاسلكي أو جداري حسب الموقع.",
    descEn: "Call + cancel, wireless or wall as installed.",
    page: "/products/NC-BTN-2K",
    buyUsd: 10,
    moq: 50,
    unitAr: "قطعة",
    unitEn: "pc",
    supplier: "Alibaba",
    url: "https://www.alibaba.com/product-detail/Hot-Sale-Cheap-Wireless-Nurse-Calling_1601240693457.html",
    notesAr: "يطابق مستقبل المحطة.",
    notesEn: "Must match the ward receiver.",
    keywords: ["زر", "نداء", "button", "nurse"],
  },
  {
    sku: "NC-PULL",
    category: "spare",
    nameAr: "شدّاد حمّام لاسلكي",
    nameEn: "Wireless bathroom pull-cord",
    descAr: "ليس بديلاً لـ Rauland إلا إذا كان التركيب كذلك.",
    descEn: "Not a Rauland drop-in unless that brand is installed.",
    page: "/products/NC-PULL",
    buyUsd: 5.5,
    moq: 1,
    unitAr: "قطعة",
    unitEn: "pc",
    supplier: "Alibaba",
    url: "https://www.alibaba.com/product-detail/Emergency-Bathroom-Service-Emergency-Pull-Cord_1693019508.html",
    notesAr: "عيادات/كيوسيرف لاسلكي.",
    notesEn: "Wireless Qserve / clinic kits.",
    keywords: ["حمّام", "شداد", "pull", "bathroom"],
  },
  {
    sku: "LCD-Q4D",
    category: "spare",
    nameAr: "شاشة رقم الانتظار",
    nameEn: "Now-serving LED display",
    descAr: "شاشة شباك 3–4 أرقام.",
    descEn: "3–4 digit counter display.",
    page: "/products/LCD-Q4D",
    buyUsd: 48,
    moq: 1,
    unitAr: "قطعة",
    unitEn: "pc",
    supplier: "Alibaba",
    url: "https://www.alibaba.com/product-introduction/Ganxin-Digital-Number-Led-Display-Board_62207062371.html",
    notesAr: "افحص بروتوكول كيوسيرف قبل التركيب.",
    notesEn: "Verify Qserve protocol before swap.",
    keywords: ["شاشة", "led", "display", "شباك"],
  },
  {
    sku: "CSAT-8",
    category: "consumable",
    nameAr: "طرفية تقييم 8 بوصة",
    nameEn: "8-inch CSAT terminal",
    descAr: "وجوه/سمايل على الشباك.",
    descEn: "Smile pad at the counter.",
    page: "/service-evaluation",
    buyUsd: 110,
    moq: 1,
    unitAr: "قطعة",
    unitEn: "pc",
    supplier: "Alibaba",
    url: "https://www.alibaba.com/product-detail/Android-8-Inch-Touch-Screen-Customer_1600228859323.html",
    notesAr: "يمكن ربط الدرجات ببصيرة.",
    notesEn: "Scores can feed Basira.",
    keywords: ["csat", "تقييم", "سمايل"],
  },
  {
    sku: "CLK-NTP",
    category: "spare",
    nameAr: "ساعة رقمية NTP/PoE تابعة",
    nameEn: "NTP/PoE slave digital clock",
    descAr: "ساعة فرعية. الشبكة الكاملة عرض سعر.",
    descEn: "Slave clock. Full network is a quote.",
    page: "/central-clocks",
    buyUsd: 90,
    moq: 1,
    unitAr: "قطعة",
    unitEn: "pc",
    supplier: "Alibaba",
    url: "https://www.alibaba.com/product-detail/Electronic-Automatic-Time-Synchronized-Digital-Clock_1600373679529.html",
    notesAr: "BDC يذكر الساعات بلا SKU.",
    notesEn: "BDC names clocks without a SKU.",
    keywords: ["ساعة", "ntp", "clock"],
  },
  {
    sku: "DISP-FLOOR",
    category: "consumable",
    nameAr: "موزّع تذاكر أرضي + ستاند",
    nameEn: "Floor ticket dispenser + stand",
    descAr: "عيادة/صيدلية — ليس نظام بنك كامل.",
    descEn: "Clinic/pharmacy — not a bank QMS.",
    page: "/products/DISP-FLOOR",
    buyUsd: 60,
    moq: 1,
    unitAr: "طقم",
    unitEn: "kit",
    supplier: "Made-in-China",
    url: "https://koqichina.en.made-in-china.com/product/AOuxhpaVvDkY/China-Take-a-Number-System-Ticket-Dispenser-with-Counter-Stand-and-1-Roll-Paper-2000-Tickets-for-Queue-Call-System.html",
    notesAr: "مع رول 2000 تذكرة.",
    notesEn: "Includes a 2,000-ticket roll.",
    keywords: ["موزع", "dispenser", "عيادة"],
  },
  {
    sku: "MT-VESA",
    category: "spare",
    nameAr: "حامل VESA 75/100",
    nameEn: "VESA 75/100 wall mount",
    descAr: "حامل شاشة/كيوسك.",
    descEn: "Screen/kiosk bracket.",
    page: "/products/MT-VESA",
    buyUsd: 12,
    moq: 1,
    unitAr: "قطعة",
    unitEn: "pc",
    supplier: "Alibaba",
    url: "https://www.alibaba.com/showroom/vesa-kiosk-mount.html",
    notesAr: "طابق VESA المصنع قبل الطلب.",
    notesEn: "Match factory VESA before PO.",
    keywords: ["vesa", "حامل", "mount"],
  },
  {
    sku: "LCD-215",
    category: "spare",
    nameAr: "شاشة لمس 21.5 بوصة كيوسك",
    nameEn: "21.5\" PCAP kiosk LCD",
    descAr: "1920×1080 لمس سعوي، إطار مفتوح لبدل شاشة الكيوسك. بيع 2×. الكيوسك الكامل عرض سعر.",
    descEn: "1920×1080 PCAP open-frame spare. Sell 2×. A complete kiosk is a quote.",
    page: "/products/LCD-215",
    buyUsd: 210,
    moq: 1,
    unitAr: "قطعة",
    unitEn: "pc",
    supplier: "Alibaba",
    url: "https://www.alibaba.com/product-detail/21-5-inch-Capacitive-Touch-Full_1601830901053.html",
    notesAr: "جوّاً. طابق فتحة المصنع.",
    notesEn: "Air. Match the factory cutout.",
    keywords: ["شاشة", "screen", "lcd", "21.5", "لمس", "touch", "سوداء"],
  },
  {
    sku: "LCD-156",
    category: "spare",
    nameAr: "شاشة مفتوحة 15.6 بوصة",
    nameEn: "15.6\" open-frame LCD",
    descAr: "HDMI/VGA لمعدن الكيوسك الصغير أو طلب الطعام.",
    descEn: "HDMI/VGA metal open-frame for smaller kiosks / food order.",
    page: "/products/LCD-156",
    buyUsd: 300,
    moq: 5,
    unitAr: "قطعة",
    unitEn: "pc",
    supplier: "GENEVISION",
    url: "https://www.components-electronic.com/product-search/pz6a3d231-cz542c6fe-15-6-open-frame-touch-screen-monitor-metal-shell-for-kiosk-and-atm.html",
    notesAr: "بدل كيوسك الطعام.",
    notesEn: "Food-kiosk spare.",
    keywords: ["15.6", "شاشة", "hdmi", "vga", "open frame"],
  },
  {
    sku: "LED-3D",
    category: "spare",
    nameAr: "شاشة عدّاد 3 أرقام + زر Next",
    nameEn: "3-digit LED + NEXT button",
    descAr: "لاسلكي 433MHz لعيادة/صيدلية. ليست نظام بنك.",
    descEn: "433 MHz clinic/pharmacy add-on. Not a bank QMS.",
    page: "/products/LED-3D",
    buyUsd: 70,
    moq: 1,
    unitAr: "طقم",
    unitEn: "kit",
    supplier: "Alibaba",
    url: "https://www.alibaba.com/product-detail/Queue-Management-System-Snappy-Queue-Management_1601386458682.html",
    notesAr: "جوّاً.",
    notesEn: "Air.",
    keywords: ["عداد", "next", "3 ارقام", "led", "شباك"],
  },
  {
    sku: "LCD-Q13",
    category: "spare",
    nameAr: "شاشة رقم لاسلكية Ycall K-Q13",
    nameEn: "Ycall K-Q13 wireless number screen",
    descAr: "3 أرقام، NEXT، حوالي 100م. بدل شاشات Ycall القائمة.",
    descEn: "3-digit, NEXT, ~100 m. Spare for existing Ycall installs.",
    page: "/products/LCD-Q13",
    buyUsd: 32,
    moq: 1,
    unitAr: "قطعة",
    unitEn: "pc",
    supplier: "Alibaba",
    url: "https://www.alibaba.com/product-introduction/Wireless-LED-Number-screen-with-NEXT_1600058714064.html",
    notesAr: "غالباً ضمن طقم K-999.",
    notesEn: "Often bundled in K-999 kits.",
    keywords: ["ycall", "kq13", "شاشة رقم", "لاسلكي"],
  },
  {
    sku: "CAB-HDMI-5",
    category: "spare",
    nameAr: "كابل HDMI 5 أمتار",
    nameEn: "HDMI cable 5 m",
    descAr: "من جهاز الانتظار لشاشة الصالة. مخزون الفان.",
    descEn: "Queue PC to lobby screen. Van stock.",
    page: "/products/CAB-HDMI-5",
    buyUsd: 3.5,
    moq: 10,
    unitAr: "قطعة",
    unitEn: "pc",
    supplier: "Alibaba",
    url: "https://www.alibaba.com/showroom/hdmi-cable-5m.html",
    notesAr: "اطلب 2.0 إن الشاشة 1080p.",
    notesEn: "HDMI 2.0 for 1080p panels.",
    keywords: ["hdmi", "كابل", "سلك شاشة", "cable", "تمديدات"],
  },
  {
    sku: "CAB-HDMI-10",
    category: "spare",
    nameAr: "كابل HDMI 10 أمتار",
    nameEn: "HDMI cable 10 m",
    descAr: "للصالة البعيدة عن الكيوسك. فوق 10م نفضّل HDMI على Cat6 مع محوّل.",
    descEn: "Long lobby runs. Beyond 10 m we prefer HDMI-over-Cat6.",
    page: "/products/CAB-HDMI-10",
    buyUsd: 6.5,
    moq: 5,
    unitAr: "قطعة",
    unitEn: "pc",
    supplier: "Alibaba",
    url: "https://www.alibaba.com/showroom/hdmi-cable-10m.html",
    notesAr: "جوّاً.",
    notesEn: "Air.",
    keywords: ["hdmi", "10", "كابل", "صالة"],
  },
  {
    sku: "CAB-VGA-5",
    category: "spare",
    nameAr: "كابل VGA 5 أمتار",
    nameEn: "VGA cable 5 m",
    descAr: "لشاشات قديمة بدون HDMI.",
    descEn: "Legacy panels without HDMI.",
    page: "/products/CAB-VGA-5",
    buyUsd: 2.4,
    moq: 10,
    unitAr: "قطعة",
    unitEn: "pc",
    supplier: "Alibaba",
    url: "https://www.alibaba.com/showroom/vga-cable-5m.html",
    notesAr: "أكد المنفذ قبل الشحن.",
    notesEn: "Confirm the port before shipping.",
    keywords: ["vga", "كابل", "شاشة قديمة"],
  },
  {
    sku: "CAB-USB-PRN",
    category: "spare",
    nameAr: "كابل USB للطابعة 3 أمتار",
    nameEn: "USB printer cable 3 m",
    descAr: "USB-A إلى USB-B. إن الكمبيوتر لا يرى الطابعة غالباً هذا الكابل.",
    descEn: "USB-A to USB-B. If the PC does not see the printer, start here.",
    page: "/products/CAB-USB-PRN",
    buyUsd: 1.8,
    moq: 10,
    unitAr: "قطعة",
    unitEn: "pc",
    supplier: "Alibaba",
    url: "https://www.alibaba.com/showroom/usb-printer-cable.html",
    notesAr: "مخزون فان.",
    notesEn: "Van stock.",
    keywords: ["usb", "كابل طابعة", "لا يرى الطابعة", "printer cable"],
  },
  {
    sku: "CAB-RS232",
    category: "spare",
    nameAr: "كابل RS232 للكيوسك",
    nameEn: "RS232 kiosk serial cable",
    descAr: "بعض طابعات KP-802 على المنفذ التسلسلي.",
    descEn: "Some KP-802 installs use serial not USB.",
    page: "/products/CAB-RS232",
    buyUsd: 2.2,
    moq: 5,
    unitAr: "قطعة",
    unitEn: "pc",
    supplier: "Alibaba",
    url: "https://www.alibaba.com/showroom/rs232-serial-cable.html",
    notesAr: "أكد DB9 ذكر/أنثى.",
    notesEn: "Confirm DB9 gender.",
    keywords: ["rs232", "serial", "تسلسلي", "كيوسك"],
  },
  {
    sku: "CAB-CAT6-3",
    category: "spare",
    nameAr: "باتش كات 6 — 3 أمتار",
    nameEn: "Cat6 patch cable 3 m",
    descAr: "شبكة الكيوسك والشاشات والساعات PoE.",
    descEn: "Kiosk, screens and PoE clocks.",
    page: "/products/CAB-CAT6-3",
    buyUsd: 1.2,
    moq: 20,
    unitAr: "قطعة",
    unitEn: "pc",
    supplier: "Alibaba",
    url: "https://www.alibaba.com/showroom/cat6-patch-cable-3m.html",
    notesAr: "مخزون فان.",
    notesEn: "Van stock.",
    keywords: ["cat6", "شبكة", "باتش", "ethernet", "كابل نت", "تمديدات"],
  },
  {
    sku: "CAB-CAT6-BOX",
    category: "spare",
    nameAr: "بكرة كات 6 — 305 متر",
    nameEn: "Cat6 UTP box 305 m",
    descAr: "تمديدات فرع جديد. التركيب في عرض السعر؛ البكرة كتالوج 2×.",
    descEn: "New-branch pulls. Labour is quoted; the box is catalog 2×.",
    page: "/products/CAB-CAT6-BOX",
    buyUsd: 48,
    moq: 1,
    unitAr: "بكرة",
    unitEn: "box",
    supplier: "Alibaba",
    url: "https://www.alibaba.com/showroom/cat6-utp-305m.html",
    notesAr: "بحر/جو حسب الكمية.",
    notesEn: "Sea/air by quantity.",
    keywords: ["cat6", "بكرة", "تمديدات", "wiring", "utp"],
  },
  {
    sku: "CAB-DC24",
    category: "spare",
    nameAr: "وصلة باور 24 فولت 2 متر",
    nameEn: "24 V DC extension 2 m",
    descAr: "من المزود لطابعة/شاشة LED عندما لا يكفي السلك الأصلي.",
    descEn: "PSU to printer/LED when the OEM lead is too short.",
    page: "/products/CAB-DC24",
    buyUsd: 1.6,
    moq: 10,
    unitAr: "قطعة",
    unitEn: "pc",
    supplier: "Alibaba",
    url: "https://www.alibaba.com/showroom/dc-24v-cable.html",
    notesAr: "أكد الفيشة 5.5×2.1.",
    notesEn: "Confirm 5.5×2.1 barrel.",
    keywords: ["باور", "dc", "24v", "وصلة", "سلك كهربا"],
  },
  {
    sku: "WIFI-AP",
    category: "spare",
    nameAr: "نقطة واي فاي للفرع",
    nameEn: "Branch Wi-Fi access point",
    descAr: "AP داخلي للكيوسك وأجهزة التقييم عندما لا توجد شبكة سلكية. ليس راوتر منزل رخيص.",
    descEn: "Indoor AP for kiosks and CSAT when there is no cable drop. Not a cheap home router.",
    page: "/products/WIFI-AP",
    buyUsd: 28,
    moq: 1,
    unitAr: "قطعة",
    unitEn: "pc",
    supplier: "Alibaba",
    url: "https://www.alibaba.com/showroom/ceiling-wifi-access-point.html",
    notesAr: "جوّاً. فضّل PoE.",
    notesEn: "Air. Prefer PoE.",
    keywords: ["واي فاي", "wifi", "راوتر", "access point", "شبكة لاسلكي"],
  },
  {
    sku: "WIFI-USB",
    category: "spare",
    nameAr: "دونجل واي فاي USB للكيوسك",
    nameEn: "USB Wi-Fi dongle for kiosk PC",
    descAr: "عندما يتعطل كرت الشبكة الداخلي.",
    descEn: "When the onboard NIC fails.",
    page: "/products/WIFI-USB",
    buyUsd: 8,
    moq: 2,
    unitAr: "قطعة",
    unitEn: "pc",
    supplier: "Alibaba",
    url: "https://www.alibaba.com/showroom/usb-wifi-adapter.html",
    notesAr: "أكد دعم ويندوز المضمّن.",
    notesEn: "Confirm embedded Windows driver.",
    keywords: ["دونجل", "usb wifi", "كيوسك نت", "wifi"],
  },
  {
    sku: "WIFI-4G",
    category: "spare",
    nameAr: "مودم 4G USB (SIM)",
    nameEn: "USB 4G modem (SIM)",
    descAr: "فرع بلا خط أرضي أو بوابة SMS. الشريحة والباقة ليست 2×.",
    descEn: "Sites with no landline, or SMS gateway. Airtime is not 2×.",
    page: "/products/WIFI-4G",
    buyUsd: 42,
    moq: 1,
    unitAr: "قطعة",
    unitEn: "pc",
    supplier: "Alibaba",
    url: "https://www.waveshare.com/wiki/SIM7600G-H_4G_HAT_%28B%29",
    notesAr: "الجهاز كتالوج. الدقائق فاتورة شهرية.",
    notesEn: "Modem is catalog. Minutes billed monthly.",
    keywords: ["4g", "مودم", "sim", "sms", "نت"],
  },
  {
    sku: "INST-EG",
    category: "fulfillment",
    priceRule: "quote",
    nameAr: "تركيب مصنع — مصر",
    nameEn: "Egypt factory installation quote",
    descAr: "أنظمة مصر تُركَّب من فريق كيوسيرف، 1000 Factory، التجمع الثالث، القاهرة الجديدة. ليست SKU شحن ولا سلة. الخليج مسار آخر (INST-ME).",
    descEn: "Egypt systems are installed by the QServe factory team at 1000 Factory, Third Settlement, New Cairo. Not a courier SKU. GCC uses INST-ME.",
    page: "/quote",
    keywords: ["تركيب", "مصنع", "INST-EG", "factory install", "القاهرة الجديدة"],
    faq: faq([
      ["هتشحنوا الكيوسك بوسطة؟", "لا في مصر. اطلبوا عرض تركيب من المصنع. البوسطة لصناديق الورق والكابلات فقط.", "Bosta for the kiosk?", "Not in Egypt. Request a factory install quote. Couriers are for paper and cable boxes only."],
    ]),
  },
  {
    sku: "INST-ME",
    category: "fulfillment",
    priceRule: "quote",
    nameAr: "تركيب محلي — الخليج (طرف ثالث)",
    nameEn: "GCC third-party installation quote",
    descAr: "الشحن من مصر (أرامكس/DHL). التركيب اختياري عبر فني/موحِّد محلي نسعّره. لا وعد أن طاقم المصنع يسافر. ليست عقداً حصرياً موقّعاً.",
    descEn: "Ship from Egypt (Aramex/DHL). Optional install via a local technician we quote. No promise that factory staff fly out. Not a signed exclusive.",
    page: "/quote",
    keywords: ["تركيب محلي", "شريك", "INST-ME", "دبي", "الرياض", "third party", "GCC"],
    faq: faq([
      ["هتيجوا دبي تركّبوا؟", "الشحن من مصر. التركيب عبر طرف ثالث محلي — نطلب عرض تركيب. ليس طيران فريق كيوسيرف افتراضياً.", "Will you install in Dubai?", "We ship from Egypt. Install is a local third-party quote — factory staff do not fly by default."],
      ["الشريك الحصري مين؟", "لا عقد حصري معلن. نسعّر فني معتمد في البلد. #تركيب", "Exclusive partner?", "No announced exclusive. We quote a certified installer in-country. #تركيب"],
    ]),
  },
  {
    sku: "SHIP-ME",
    category: "fulfillment",
    priceRule: "quote",
    nameAr: "تقدير شحن للخليج",
    nameEn: "Middle East freight estimate",
    descAr: "تقدير ثم اطلب عرض شحن. أرامكس/DHL/UPS/FedEx/سمسا. الجمارك على المستلم ما لم يُكتب في أمر الشراء. لا رقم شحن وهمي في السلة.",
    descEn: "Estimate then request a shipping quote. Aramex/DHL/UPS/FedEx/SMSA. Duties on the buyer unless the PO says otherwise. No invented freight figure in the cart.",
    page: "/quote",
    keywords: ["شحن", "SHIP-ME", "أرامكس", "dhl", "freight", "خليج"],
    faq: faq([
      ["سعر الشحن على السلة؟", "لا رقم نهائي في الشات. تقدير ثم اطلب عرض شحن. #شحن", "Freight on the cart?", "No final figure in chat. Estimate, then request a shipping quote. #شحن"],
    ]),
  },
];

function sellOf(buy) {
  return Number((Number(buy) * 2).toFixed(4));
}

function enrichCatalog(item) {
  const sellUsd = sellOf(item.buyUsd);
  const priceRule = item.priceRule || "catalog-2x";
  return {
    ...item,
    priceRule,
    sellUsd,
    marginPct: 100,
    faq: item.faq || CATALOG_FAQ(item.nameAr, item.nameEn, sellUsd, item.unitAr, item.unitEn, item.moq),
  };
}

export function allProducts(overrides = {}) {
  const extras = PRODUCTS.map((p) => ({ ...p, sellUsd: p.sellUsd ?? null, buyUsd: p.buyUsd ?? null }));
  const catalog = CATALOG_SEED.map(enrichCatalog);
  const merged = [...extras, ...catalog].map((p) => {
    const o = overrides[p.sku];
    return o ? { ...p, ...o, sku: p.sku, faq: o.faq || p.faq } : p;
  });
  return merged;
}

export function catalogItems(overrides) {
  return allProducts(overrides).filter((p) => p.buyUsd != null);
}

export function publicProducts(overrides) {
  return allProducts(overrides).map((p) => ({
    sku: p.sku,
    category: p.category,
    priceRule: p.priceRule,
    nameAr: p.nameAr,
    nameEn: p.nameEn,
    descAr: p.descAr,
    descEn: p.descEn,
    page: p.page,
    sellUsd: p.priceRule === "catalog-2x" ? p.sellUsd : null,
    unitAr: p.unitAr || (p.priceRule === "quote" ? "بند" : "قطعة"),
    unitEn: p.unitEn || (p.priceRule === "quote" ? "line" : "pc"),
    faq: p.faq,
    keywords: p.keywords || [],
  }));
}

function norm(s) {
  return String(s || "")
    .toLowerCase()
    .replace(/[أإآ]/g, "ا")
    .replace(/ة/g, "ه")
    .replace(/ى/g, "ي")
    .replace(/[^\p{L}\p{N}\s×x-]/gu, " ");
}

function tokens(q) {
  return norm(q)
    .split(/\s+/)
    .filter((t) => t.length >= 2);
}

const INTENT = [
  { re: /طابع.{0,12}كيوسك|كيوسك.{0,12}(وقف|عطل|لا تطبع)|kiosk printer|printer (stopped|jam)/i, boost: ["KSK-KP802", "TPH-80", "TH-80X80", "PSU-24V25", "SVC-EMERG", "AMC-STD"] },
  { re: /3\s*شبابيك|ثلاثه شبابيك|three window|فرع بنك/i, boost: ["SYS-PKG-3WIN", "SYS-QUEUE", "ANL-TPL-BANK", "TH-80X80", "AMC-STD"] },
  { re: /عندنا نظام|اشترينا|مرك[بّ]|installed|already have|after.?sale|بعد البيع/i, boost: ["AMC-STD", "AMC-PLUS", "AMC-INS", "SVC-EMERG"] },
  { re: /عقد صيان|صيان[ةه] سنو|amc|احتياطي قطع/i, boost: ["AMC-STD", "AMC-PLUS", "AMC-INS", "WTY-EXT"] },
  { re: /صيان|عطل|وقف|repair|down|jam|لا تطبع|أعطال/i, boost: ["AMC-STD", "SVC-EMERG", "SVC-REMOTE", "AMC-PLUS"] },
  { re: /بصير|basira|ربح|برنامج|software/i, boost: ["ANL-SETUP", "ANL-BR", "AMC-INS"] },
  { re: /رول|ورق|حراري|roll|thermal/i, boost: ["TH-80X80", "TH-60X60", "TH-80X70"] },
  { re: /ممر|ممرض|سرير|nurse|cord|سلك نداء/i, boost: ["SYS-NURSE", "NC-CORD-635", "NC-BTN-2K", "NC-PULL", "SLA-HOSP"] },
  { re: /hdmi|vga|كابل|تمديد|cat6|كات 6|usb طابع|سلك شاش|wiring|cable/i, boost: ["CAB-HDMI-5", "CAB-HDMI-10", "CAB-CAT6-3", "CAB-CAT6-BOX", "CAB-USB-PRN", "CAB-VGA-5"] },
  { re: /واي فاي|wifi|wi-?fi|راوتر|access point|دونجل|4g|مودم|شبكة لاس/i, boost: ["WIFI-AP", "WIFI-USB", "WIFI-4G", "CAB-CAT6-3"] },
  { re: /شاشة|lcd|led|لمس|screen|monitor|سوداء|لا تضيء/i, boost: ["LCD-215", "LCD-156", "LCD-Q4D", "LED-3D", "LCD-Q13", "CAB-HDMI-5"] },
  { re: /شحن|أرامكس|aramex|dhl|freight|خليج|دبي|رياض/i, boost: ["SHIP-ME", "INST-ME"] },
  { re: /تركيب مصنع|INST-EG|بوسطة|bosta/i, boost: ["INST-EG"] },
  { re: /تركيب محلي|INST-ME|شريك محلي|third.?party/i, boost: ["INST-ME", "SHIP-ME"] },
];

export function searchKb(query, overrides) {
  const list = allProducts(overrides);
  const ts = tokens(query);
  const qn = norm(query);
  if (!qn.trim()) return [];
  const scores = new Map(list.map((p) => [p.sku, 0]));
  for (const { re, boost } of INTENT) {
    if (re.test(query)) for (const sku of boost) scores.set(sku, (scores.get(sku) || 0) + 8);
  }
  for (const p of list) {
    const hay = norm(
      [p.sku, p.category, p.nameAr, p.nameEn, p.descAr, p.descEn, ...(p.keywords || []), ...(p.faq || []).flatMap((f) => [f.qAr, f.aAr, f.qEn, f.aEn])].join(" "),
    );
    let s = scores.get(p.sku) || 0;
    if (hay.includes(qn) && qn.length > 4) s += 12;
    for (const t of ts) {
      if (hay.includes(t)) s += t.length > 4 ? 3 : 2;
      if (norm(p.sku) === t) s += 10;
    }
    scores.set(p.sku, s);
  }
  return list
    .map((p) => ({ ...p, score: scores.get(p.sku) || 0 }))
    .filter((p) => p.score > 0)
    .sort((a, b) => b.score - a.score)
    .slice(0, 3);
}

export function bySku(sku, overrides) {
  return allProducts(overrides).find((p) => p.sku === sku);
}

export function byPage(path, overrides) {
  const bare = String(path || "").replace(/^\/en/, "") || "/";
  return allProducts(overrides).filter((p) => p.page === bare || p.page === path);
}

export async function webFallback(query) {
  const q = `${query} queue kiosk nurse call Egypt`;
  try {
    const url = `https://api.duckduckgo.com/?q=${encodeURIComponent(q)}&format=json&no_html=1&skip_disambig=1`;
    const res = await fetch(url, { headers: { accept: "application/json" } });
    if (!res.ok) return "";
    const j = await res.json();
    const bits = [];
    if (j.AbstractText) bits.push(j.AbstractText);
    if (j.Heading) bits.push(j.Heading);
    for (const t of j.RelatedTopics || []) {
      if (t.Text) bits.push(t.Text);
      if (Array.isArray(t.Topics)) for (const x of t.Topics.slice(0, 2)) if (x.Text) bits.push(x.Text);
    }
    return bits.join("\n").slice(0, 1200);
  } catch {
    return "";
  }
}
