import type { Locale } from "./i18n";
import type { Product } from "./content";

type Copy = Pick<Product, "nav" | "title" | "h1" | "meta" | "kicker" | "summary" | "paragraphs" | "bullets" | "components" | "imageAlt">;

export const enCopy: Record<string, Copy> = {
  "queuing-system": {
    nav: "Queue management",
    title: "Queue management system Egypt | QServe",
    h1: "Queue system components",
    meta: "QServe queue system components: ticket printer or kiosk, LED displays, call unit, central management, and reporting software.",
    kicker: "QServe",
    summary: "A complete hardware and software system",
    paragraphs: [],
    bullets: [],
    components: [
      { title: "Ticket printer or ticket-print kiosk", text: "Issues digital waiting tickets quickly, with QR print and multiple service options." },
      { title: "Ticket-number display", text: "High-clarity LED screens show current waiting numbers and service data for visitors." },
      { title: "Clinic or staff number display", text: "Side screens at each desk or clinic to direct the visitor to the right service point." },
      { title: "Call unit to pick the service or request the number", text: "Staff call visitors one by one, with clear voice over the speakers." },
      { title: "Central management system linking every component", text: "Software that joins all parts of the system, with remote admin and data analysis." },
      { title: "Queue-system reporting software", text: "An analytics board for average service time, visitor count, and staff performance." },
    ],
    imageAlt: "QServe queue management system components",
  },
  "nurse-call-system": {
    nav: "Nurse call system",
    title: "Nurse call system Egypt | QServe",
    h1: "Nurse call system components",
    meta: "QServe nurse call system components: call units, display panel, control unit, and alarm devices.",
    kicker: "QServe",
    summary: "A nurse call system for hospitals and clinics",
    paragraphs: [
      "The nurse call system is made of several core parts that work together so the system runs well and staff can answer fast. Here are the main parts of this system:",
    ],
    bullets: [
      "Fast response in emergencies",
      "A clear improvement in patient care",
      "Less stress on medical staff",
      "Close follow-up of patients around the clock",
      "Automatic logging of call and response times",
      "Fewer medical errors from delay",
      "Better patient and family satisfaction with the service",
    ],
    components: [
      { title: "Call units", text: "Fitted beside the patient bed or in the bathroom, so the patient can ask for help." },
      { title: "Display panel", text: "Fitted in the nurses’ room, and shows alerts when a patient calls." },
      { title: "Control unit", text: "Used to manage the system and set response priorities." },
      { title: "Alarm devices", text: "Sound or light alerts to notify nurses." },
    ],
    imageAlt: "QServe — nurse call system · NURSE CALL SYSTEM",
  },
  "self-service-kiosks": {
    nav: "Self-service kiosks",
    title: "Self service kiosk Egypt | QServe",
    h1: "Self service kiosk Egypt",
    meta: "Self service kiosk Egypt from QServe: ticket, inquiry, or order and pay.",
    kicker: "Self service kiosk Egypt",
    summary: "Self service kiosk Egypt: ticket, inquiry, or order and pay at the branch door.",
    paragraphs: ["Banking, food order, government inquiry and hotel check-in — integrated with queue and payments."],
    bullets: ["Touch screens", "Card/e-pay", "Restaurant, bank, government", "Queue integration"],
    components: [
      { title: "Bank / government", text: "Inquiry, ticket, receipts." },
      { title: "Food & pay", text: "Menu, order, pay without the cashier line." },
      { title: "Hotel arrival", text: "Simple check-in and guest info." },
    ],
    imageAlt: "Qserve Egypt self-service kiosk in a bank",
  },
  "smart-boards": {
    nav: "Interactive boards",
    title: "Smart interactive boards | Qserve Egypt",
    h1: "Smart interactive boards",
    meta: "4K touch boards for classrooms, meetings and training.",
    kicker: "Smart Interactive Boards",
    summary: "4K touch with onboard compute for education and meetings.",
    paragraphs: ["Classroom and boardroom collaboration with 4K and site display integration."],
    bullets: ["4K", "Built-in processor", "Education, training, meetings"],
    components: [{ title: "Interactive panel", text: "Write, share, multi-source display." }],
    imageAlt: "Qserve Egypt interactive displays",
  },
  "central-clocks": {
    nav: "Master clocks",
    title: "Master clock systems | Qserve Egypt",
    h1: "Master clock systems",
    meta: "Synchronised digital clocks for every site — banks and hospitals.",
    kicker: "Master Clock System",
    summary: "One time source across buildings, with indoor and outdoor clocks.",
    paragraphs: ["Unify time in branches, corridors and offices, including outdoor clocks for multi-building campuses."],
    bullets: ["Site-wide sync", "Indoor and outdoor", "Hospitals and banks"],
    components: [
      { title: "Master clock", text: "Time source for all slave clocks." },
      { title: "Secondary clocks", text: "Unified digital display in halls." },
    ],
    imageAlt: "Qserve Egypt synchronised clocks",
  },
  "digital-signage": {
    nav: "Digital signage",
    title: "Digital signage | Qserve Egypt",
    h1: "Digital signage",
    meta: "LED/LCD networks for information and ads in banks, airports and retail.",
    kicker: "Digital Signage",
    summary: "Smart screens for information and advertising.",
    paragraphs: ["LED and LCD networks with scheduled operational and commercial content."],
    bullets: ["LED / LCD", "Content scheduling", "Airports and retail branches"],
    components: [{ title: "Display network", text: "One content desk for many screens." }],
    imageAlt: "Qserve Egypt digital signage",
  },
  "service-evaluation": {
    nav: "Service scoring",
    title: "Service evaluation | Qserve Egypt",
    h1: "Service evaluation",
    meta: "CSAT terminals for government and bank counters.",
    kicker: "CSAT / Service Evaluation",
    summary: "Capture satisfaction at the counter, instantly.",
    paragraphs: ["Placed after service to collect scores per window for branch quality."],
    bullets: ["Instant post-service score", "Reports per window", "Government and banks"],
    components: [{ title: "Score pad", text: "Clear satisfaction buttons in seconds." }],
    imageAlt: "Qserve Egypt CSAT terminal",
  },
  "interactive-maps": {
    nav: "Wayfinding maps",
    title: "Interactive maps | Qserve Egypt",
    h1: "Interactive wayfinding",
    meta: "Touch wayfinding for hospitals and large buildings.",
    kicker: "Interactive Wayfinding",
    summary: "Help visitors find clinics and departments on a touch map.",
    paragraphs: ["Search a clinic or department and show the walking path."],
    bullets: ["Visitor guidance", "Department search", "Multi-floor hospitals"],
    components: [{ title: "Touch map", text: "Path from the visitor to the destination." }],
    imageAlt: "Qserve Egypt hospital wayfinding",
  },
  "proximity-card": {
    nav: "Proximity cards",
    title: "Proximity cards | Qserve Egypt",
    h1: "Proximity cards",
    meta: "RFID access and attendance cards.",
    kicker: "Proximity Card",
    summary: "RFID cards for doors and time attendance.",
    paragraphs: ["Used with Qserve Egypt access and attendance systems."],
    bullets: ["RFID", "Access control", "Attendance"],
    components: [],
    imageAlt: "Qserve Egypt proximity cards",
  },
  "mifare-card": {
    nav: "Mifare cards",
    title: "Mifare cards | Qserve Egypt",
    h1: "Mifare cards",
    meta: "Secure NFC Mifare cards for multi-application use.",
    kicker: "Mifare Card",
    summary: "High-security NFC cards for access, ID and on-site payments.",
    paragraphs: ["Multi-use: access, identity and campus payments."],
    bullets: ["High security", "NFC", "Multi-application"],
    components: [],
    imageAlt: "Qserve Egypt smart cards",
  },
  "id-card-printing": {
    nav: "ID card printing",
    title: "ID card printing | Qserve Egypt",
    h1: "Plastic ID printing",
    meta: "Staff and membership ID printing.",
    kicker: "ID Card Printing",
    summary: "High-quality staff and membership cards, ready for access systems.",
    paragraphs: ["Employee and membership cards that can join the access stack."],
    bullets: ["Staff IDs", "Membership", "On-brand design"],
    components: [],
    imageAlt: "Qserve Egypt ID printing",
  },
  "id-card-printers": {
    nav: "ID printers",
    title: "ID card printers | Qserve Egypt",
    h1: "ID card printers",
    meta: "Zebra, Evolis and HID printers with local support.",
    kicker: "ID Card Printers",
    summary: "Global printer brands, supplied and supported in Egypt.",
    paragraphs: ["Supply plus local operation support from Qserve Egypt."],
    bullets: ["Zebra", "Evolis", "HID"],
    components: [],
    imageAlt: "Qserve Egypt card printers",
  },
};

export function localizedProduct(product: Product, locale: Locale): Product {
  if (locale !== "en") return product;
  const extra = enCopy[product.slug];
  if (!extra) return product;
  return { ...product, ...extra };
}
